### ISSUE TITLE
Add Filter to header.php

### ISSUE THREAD

**Issue by webbyhiren** [luicephillips/hellobase#17]
**Apply Filters required**

- wp_nav_menu arguments

**Comment by webbyhiren** [comment]
An Improvement Required:

Replace existing code of `wp_nav_menu` with

`$defaults = array(
                'theme_location' => 'menu-1',
            );
            /**
             * Filter for Navigation Menu Arguments
             * @package Hellobase
             * @since 1.0.0
             */
            wp_nav_menu( apply_filters( 'hellobase_menu_args', $defaults ) );`

**Comment by dharat** [comment]
Add filter header in primary menu
