### ISSUE TITLE
Add Support for Post Formats 

### ISSUE THREAD

**Issue by webbyhiren** [luicephillips/hellobase#18]
- Add Post Format Support to Theme
- Add Filter for Post Format
- Add Comments

**Comment by dharat** [comment]
Added Post Format Support

**Comment by webbyhiren** [comment]
An improvement required:

Replace existing code of Post Format with
`/* Added Post Format Supports */
    $post_format_args = array(
        'image',
        'gallery',
        'video'
    );
    add_theme_support( 'post-formats', apply_filters( 'hellobase_post_format_arguments', $post_format_args ) );`

**Comment by dharat** [comment]
Add post format filter
