### ISSUE TITLE
Remove few items from base-functions.php

### ISSUE THREAD

**Issue by webbyhiren** [luicephillips/hellobase#19]
Remove below mentioned code :
https://github.com/luicephillips/hellobase/blob/master/inc/base-functions.php#L61
https://github.com/luicephillips/hellobase/blob/master/inc/base-functions.php#L101
https://github.com/luicephillips/hellobase/blob/master/inc/base-functions.php#L104
https://github.com/luicephillips/hellobase/blob/master/inc/base-functions.php#L105

**Comment by webbyhiren** [comment]
Improve Indentation as well for base-functions.php file

**Comment by dharat** [comment]
Removed
