### ISSUE TITLE
Add New Filter for CF7

### ISSUE THREAD

**Issue by webbyhiren** [luicephillips/hellobase#22]
Add `apply_filters` to array arguments placed in file https://github.com/luicephillips/hellobase/blob/master/classes/cf7.php#L25

**Comment by webbyhiren** [comment]
Add filter information to the documentation under Wiki section.
https://github.com/luicephillips/hellobase/wiki/Developer-Documentation

**Comment by dharat** [comment]
Add CF& filter with name  hellobase_cf7_include_pages
