### ISSUE TITLE
Add Smart Breadcrumb function

### ISSUE THREAD

**Issue by luicephillips** [luicephillips/hellobase#24]
We must have breadcrumbs in our base theme as it helps in SEO as well.

So we will create a function or class which will act as general and have maximum customization using hooks.

We should also have a shortcode for the same with Quicktags

- [ ] Function Class
- [ ] Shortcode Creation
- [ ] Testing with Child Theme
- [ ] Documentation

**Comment by dharat** [comment]
Added Filters of separators and Home page name in breadcrumb.
Use with function hellobase_breadcrumbs()
Shortcode [HellobaseBreadcrumbs]
Added QuickTags in editors
