### ISSUE TITLE
Existing CPT Function to be improved

### ISSUE THREAD

**Issue by luicephillips** [luicephillips/hellobase#27]
Need to improve existing CPT function `hellobase_register_custom_post_type_callback`.

So that we can easily modify or extend any Custom Post Type.

Also, make sure we have Child Theme Support and extendability using Child Theme.

- [ ] Improvement of existing function
- [ ] Adding Hooks required
- [ ] Testing with Child Theme
- [ ] Documentation

**Comment by dharat** [comment]
Add Filters of arguments in CPT
