### ISSUE TITLE
Custom Taxonomy Option same as CPT

### ISSUE THREAD

**Issue by luicephillips** [luicephillips/hellobase#28]
We need to have functionality to create custom taxonomy same as custom post types.

It should be extendable using Child theme.

- [ ] Implementation
- [ ] Testing with Child Theme
- [ ] Documentation

**Comment by dharat** [comment]
We need to have functionality to create custom taxonomy same as custom post types. **DONE**

It should be extendable using Child theme. - **Extends in by filter in child theme**
