### ISSUE TITLE
Plugin Installation restriction for client

### ISSUE THREAD

**Issue by luicephillips** [luicephillips/hellobase#3]
Restrict Client User roles for plugin installation

Do Research
Test
Documentation

**Comment by dharat** [comment]
Add New role of sub admin. In Sub admin role, user has no permission to add plugin.

**Comment by luicephillips** [comment]
Manage it using Action Hook so that we can easily disable the same from child theme

**Comment by dharat** [comment]
Add Filter of Capabilities of sub admin role
